name: build social-face-project app

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
    
      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: '21.x'

      - name: Install dependencies
        working-directory: ./social-face-project
        run: npm ci

      - name: Run unit tests
        working-directory: ./social-face-project
        run: npm test -- --no-watch --no-progress --browsers=ChromeHeadless

      - name: Run Cypress Tests
        working-directory: ./social-face-project
        run: npx cypress run --config-file cypress.config.ts --record --key ${{ secrets.CYPRESS_KEY }} --browser chrome --headless --parallel
      
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./social-face-project/dist/social-face-project/browser
