name: build social-face-project app

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
    
      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: '21.x'

      - name: Install dependencies
        run: |
          cd ./social-face-project
          npm ci

      - name: Run unit tests
        run: |
          cd ./social-face-project
          npm test -- --no-watch --no-progress --browsers=ChromeHeadless
